name: build and run tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    # Install dependencies
    - name: Install googletest
      uses: cvpkg/googletest-action@v0.1
      with:
        googletest_tag: 'release-1.11.0'

    - name: .pre 
      working-directory: ${{runner.workspace}}/uast
      shell: bash
      run: |         
          pip install wheel
          pip install cpplint   

    # Build project
    - name: build
      working-directory: ${{runner.workspace}}/build/
      shell: bash
      run: |
          cd build
          cmake ..
          make all

    - name: Check code style
      working-directory: ${{runner.workspace}}/uast
      shell: bash
      run: python -m cpplint --recursive --exclude=source/catch.hpp --filter=-legal/copyright,-build/include_subdir source/* 

    # run tests
    - name: test
      working-directory: ${{runner.workspace}}/build/test/
      shell: bash
      run: lab0_tst 